# Generated by Django 5.2.3 on 2025-07-27 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-issue_date']},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certificate_pdf',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certificate_url',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='title',
        ),
        migrations.AddField(
            model_name='certification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='credential_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='certification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='issuing_organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma separated list of skills', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
