# Generated by Django 5.2.3 on 2025-07-27 10:20

import django.core.validators
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(blank=True, help_text='Upload certificate image (JPG/PNG)', null=True, upload_to=portfolio.models.certificate_upload_path),
        ),
        migrations.AddField(
            model_name='certification',
            name='certificate_pdf',
            field=models.FileField(blank=True, help_text='Upload certificate PDF', null=True, upload_to=portfolio.models.certificate_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
